In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("D:\Downloads\customer_shopping.csv")

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,NaN,NaN,Male
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Express,Yes,Yes,2,Cash,Fortnightly,NaN,NaN,Female
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,NaN,NaN,NaN
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,NaN,NaN,NaN
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,NaN,NaN,NaN

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases,Unnamed: 18,Unnamed: 19
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000,0.0,0.0
mean,1950.500000,44.068462,59.764359,3.750065,25.351538,NaN,NaN
std,1125.977353,15.207589,23.685392,0.716983,14.447125,NaN,NaN
min,1.000000,18.000000,20.000000,2.500000,1.000000,NaN,NaN
25%,975.750000,31.000000,39.000000,3.100000,13.000000,NaN,NaN
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,NaN,NaN
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,NaN,NaN
max,3900.000000,70.000000,100.000000,5.000000,50.000000,NaN,NaN

In [5]:
print(f'The Shape of DataFrame = {df.shape}')
df.info()

The Shape of DataFrame = (3900, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
 18  Unnamed: 18             0 non-null      float64
 19  Unnamed: 19             0 non-null      float64
 20  Unnamed: 20             2 non-null      object
dtypes: float64(3), int64(4), object(14)
memory usage: 640.0+ KB

In [6]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")  
df.columns = df.columns.str.replace("purchase_amount_(usd)","purchase_amount")  
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20'],
      dtype='object')

In [7]:
df["review_rating"] = df.groupby("category")["review_rating"].transform(lambda x : x.fillna(x.median))

In [8]:
df.isnull().sum()

customer_id                  0
age                          0
gender                       0
item_purchased               0
category                     0
purchase_amount              0
location                     0
size                         0
color                        0
season                       0
review_rating                0
subscription_status          0
shipping_type                0
discount_applied             0
promo_code_used              0
previous_purchases           0
payment_method               0
frequency_of_purchases       0
unnamed:_18               3900
unnamed:_19               3900
unnamed:_20               3898
dtype: int64

In [9]:
bins = [0, 24, 39, 54, 100]
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [10]:
df[["age","age_group"]].head()

   age    age_group
0   55       Senior
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [11]:
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [12]:
df[['purchase_frequency_days','frequency_of_purchases']].head()

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually

In [13]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,...,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,unnamed:_18,unnamed:_19,unnamed:_20,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Yes,14,Venmo,Fortnightly,NaN,NaN,Male,Senior,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Yes,2,Cash,Fortnightly,NaN,NaN,Female,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Yes,23,Credit Card,Weekly,NaN,NaN,NaN,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,Yes,49,PayPal,Weekly,NaN,NaN,NaN,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Yes,31,PayPal,Annually,NaN,NaN,NaN,Middle-aged,365

In [14]:
(df["discount_applied"] == df["promo_code_used"]).all()

np.True_

In [15]:
df  = df.drop("promo_code_used",axis=1)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   object
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  unnamed:_18              0 non-null      float64
 18  unnamed:_19              0 non-null      float64
 19  unnamed:_20              2 non-null      object
 20  age_group                3900 non-null   category
 21  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(2), int64(5), object(14)
memory usage: 644.0+ KB

In [17]:
df["review_rating"] = pd.to_numeric(df['review_rating'], errors='coerce'  )

In [20]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\programdata\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [21]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Encode password (important if special characters exist)
username = "root"
password = quote_plus("dheeraj@2007")
host = "localhost"
port = "3306"
database = "customer"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Example DataFrame

df.to_sql("mytable", engine, if_exists="replace", index=False)

3900